#!/bin/bash
# Script to run all the python stuff

# Clean out the images directory
rm -r images/*

########################## Reddit Downloader ###########################
# Download images from me_irl
python redditDownloader.py dankmemes


########################## Keyword Gatherer ############################
# For each downloaded image gather the keywords from Google
for file in images/*.jpg
do
  echo ${file##*/}
  python keywordGatherer.py $file
done

########################## Keyword Condenser ###########################
# Find the most common keyword in the keywords.txt file
python keywordCondenser.py


######################### Google Downloader ############################
# Download an image using the top keyword
python googleDownloader.py

######################### Meme Creator #################################
# Create that spicy meme
python memeCreator.py "./createdMemes/000001.jpg" "ME TOO" "THANKS"


######################### Reddit Upload ###############################
# Upload to me_irl through a GUI script
~/Downloads/si/runsikulix -r ~/_Code/meirlbot/redditPost.skl

echo "COMPELETE"
