#!/bin/bash
# Script to run all the python stuff
# Clean out the images directory
rm -r images/*
rm keywordsCondensed.txt
rm keywords.txt
rm -r createdMemes/*

########################## Reddit Downloader ###########################
# Download images from me_irl
python redditDownloader.py


########################## Keyword Gatherer ############################
# For each downloaded image gather the keywords from Google
python captionFinder.py


######################### Google Downloader ############################
# Download an image using the top keyword
python googleDownloader.py

######################### Meme Creator #################################
# Create that spicy meme
python memeCreator.py


######################### Reddit Upload ###############################
# Upload to me_irl through a GUI script
#~/Downloads/si/runsikulix -r ~/_Code/meirlbot/redditPost.skl

open createdMemes/


######################## Update Flag Reset ############################
# Reset all the update flags in the database to false
#python resetUpdateFlags.py

echo "COMPELETE with $(ls -l ./images | wc -l) images used"
